package ticketmachine;

/**
 *
 * @author Zubeer
 */
public enum Operation {
    SELLING_TICKET, SELECTING_PAYMENT, BUYING_SINGLE,BUYING_SEASON, BUYING_PHYSICAL, 
    BUYING_PSEASON, BUYING_PTICKET, CHOOSING_TICKET, INSERTING_COINS, INSERTING_CCARD, 
    LOGGING_IN, PRINTING_TICKET, CREATING_USER
}
