/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-07-11 10:21:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.progettol.webserver.beans.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./include/footer.html", Long.valueOf(1499638966266L));
    _jspx_dependants.put("/./include/header.jsp", Long.valueOf(1499638966266L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/ticket/css/style.css\">\n");
      out.write("\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top headerNavbar\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <div class=\"navbar-header\">\n");
      out.write("      <a class=\"navbar-brand logo-container\" href=\"/ticket/\">\n");
      out.write("        <img alt=\"Brand\" class=\"img-responsive logo\" src=\"http://freevector.co/wp-content/uploads/2014/06/84015-kick-scooter.png\"> <p class=\"logoText\">MonopattinoAirway</p>\n");
      out.write("      </a>\n");
      out.write("      </div>\n");
User user = (User)session.getAttribute("user");
      out.write('\n');
      out.write('\n');
 if(user!=null){ 
      out.write("\n");
      out.write("\t<p class=\"navbar-text navbar-right\"> <a href=\"/ticket/profile.jsp\" class=\"navbar-link\">visita il profilo: ");
      out.print(user.getUsername());
      out.write("</a></p>\n");
      out.write("\t<p class=\"navbar-text navbar-right\"><a href=\"/ticket/web/?action=logout\" class=\"navbar-link\">Logout</a></p>\n");
}else{
      out.write("\n");
      out.write("\t<p class=\"navbar-text navbar-right\"><a href=\"/ticket/login.jsp\" class=\"navbar-link\">Login</a></p>\n");
      out.write("\t<p class=\"navbar-text navbar-right\"><a href=\"/ticket/registration.jsp\" class=\"navbar-link\">Registrazione</a></p>\n");
      out.write("\n");
} 
      out.write("\t\n");
      out.write("\n");
      out.write("\t\n");
      out.write("  </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("<div class=\"container\">\n");
      out.write("\t<div class=\"jumbotron homepageContainer\">\n");
      out.write("\t\n");
      out.write("\t  <h1>Benvenuto sul MonopattinoAirway!</h1>\n");
      out.write("\t  <p>Il sito è in versione limitata (monopattino), entra nella community dei viaggiatori.</p>\n");
      out.write("\t  <p><a class=\"btn btn-success btn-lg\" href=\"registration.jsp\" role=\"button\">Registrati</a>\n");
      out.write("\t  <a class=\"btn btn-default btn-lg\" href=\"login.jsp\" role=\"button\">Login</a>\n");
      out.write("\t  </p>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
