CREATE SCHEMA `emettitrici` ;

USE `emettitrici`;

CREATE TABLE `emettitrici`.`users` (
  `USERNAME` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `SURNAME` VARCHAR(45) NOT NULL,
  `CF` VARCHAR(45) NOT NULL,
  `PSW` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USERNAME`));
  
CREATE TABLE `emettitrici`.`tickets` (
  `CODE` VARCHAR(45) NOT NULL,
  `TYPE` VARCHAR(45) NOT NULL,
  `EXPIRE_TIME` VARCHAR(45) NULL,
  `USER` VARCHAR(45) NULL,
  PRIMARY KEY (`CODE`));
  
CREATE TABLE `emettitrici`.`fines` (
  `ID` INT(11) NOT NULL,
  `CF` VARCHAR(45) NOT NULL,
  `AMOUNT` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `emettitrici`.`collectors` (
  `USERNAME` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `SURNAME` VARCHAR(45) NOT NULL,
  `CF` VARCHAR(45) NOT NULL,
  `PSW` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USERNAME`));